version: '3.8'

services:
  backend:
    build:
      context: ./web/backend
      dockerfile: ../../docker/Dockerfile.backend
    volumes:
      - ./recon/output:/app/output:ro
      - ./web/backend/server.js:/app/server.js:ro
      - ./web/backend/check-paths.js:/app/check-paths.js:ro
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - autobounty-network

  frontend:
    build:
      context: ./web/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    volumes:
      - ./recon/output:/app/output:ro
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - autobounty-network

networks:
  autobounty-network:
    driver: bridge 