version: '3.8'

services:
  recon:
    build:
      context: ./recon
      dockerfile: ../docker/Dockerfile.recon
    volumes:
      - ./recon:/app/recon
    working_dir: /app/recon
    entrypoint: ["sh", "run_recon.sh"]
    networks:
      - autobounty-network

  nuclei:
    build:
      context: ./recon
      dockerfile: ../docker/Dockerfile.nuclei
    volumes:
      - ./recon/:/app/recon
    working_dir: /app/recon
    entrypoint: ["sh", "run_nuclei.sh"]
    networks:
      - autobounty-network

  gowitness:
    build:
      context: ./recon
      dockerfile: ../docker/Dockerfile.gowitness
    volumes:
      - ./recon/:/app/recon
    working_dir: /app/recon
    entrypoint: ["sh", "run_gowitness.sh"]
    networks:
      - autobounty-network

networks:
  autobounty-network:
    driver: bridge
